recipe_platform_app/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

recipe_platform_app/recipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from recipe.views import *
from user.views import LoginUser
from user.views import profile

app_name = 'recipe'

urlpatterns = [
                  path('play-video/', play_video, name="play-video"),
                  path('', home, name='home_page'),
                  path("profile/", profile, name='user_profile'),
                  path("login/", LoginUser.as_view(), name='login'),
                  path('recipes-list', RecipeListView.as_view(), name='recipe_list'),
                  path('recipe/<int:pk>', RecipeDetailView.as_view(), name='recipe_detail'),
                  path('recipe/create/', RecipeCreateView.as_view(), name='create_recipe'),
                  path('recipe/<int:pk>/update/', RecipeUpdateView.as_view(), name='update_recipe'),
                  path('recipe/<int:pk>/delete', RecipeDeleteView.as_view(), name='delete_recipe'),
                  path('about/', about, name='about'),
                  path('recipe/<int:pk>/add-comment', add_comment, name='add-comment'),
                  path('recipe/<int:pk>/delete-comment', comment_delete, name='delete-comment'),
                  path('like/<int:pk>', LikeView, name='like_recipe'),
                  path('add_category/', AddCategoryView.as_view(), name='add-category'),
                  path('category/<str:cats>/', CategoryView, name='category'),
                  path('category_list/', CategoryListView, name='category_list'),
                  path('search/', search, name='search_page'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/recipe_platform_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path('oauth/', include('social_django.urls', namespace='social')),
               path('admin/', admin.site.urls),
               path('', include('recipe.urls')),
               path('cart/', include('cart.urls', namespace='cart')),
               path('store/', include('store.urls', namespace='store')),

               path('accounts/', include('user.urls')),

               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from store.views import *

app_name = 'store'

urlpatterns = [
                  path('', store_page, name='store_page'),
                  path('<slug:category_slug>', store_page, name='product_list_by_category'),
                  path('<int:id>/<slug:slug>', product_detail, name='product_detail'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import LoginUser, ChangePassword, RegisterUser, profile

app_name = "user"
urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("changepassword/", ChangePassword.as_view(), name="password_change"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("profile/", profile, name="user_profile")
]

recipe_platform_app/user/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image

from .constants import COUNTRIES_CHOICES


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=40, null=True)
    last_name = models.CharField(max_length=50, null=True)
    email = models.EmailField()
    website_url = models.CharField(max_length=255, blank=True, null=True)
    facebook_url = models.CharField(max_length=255, blank=True, null=True)
    twitter_url = models.CharField(max_length=255, blank=True, null=True)
    instagram_url = models.CharField(max_length=255, blank=True, null=True)
    pinterest_url = models.CharField(max_length=255, blank=True, null=True)
    country_of_origin = models.CharField(max_length=30, null=True, blank=True, default="CV", choices=COUNTRIES_CHOICES)
    biography = models.TextField()
    avatar = models.ImageField(default="default.png", upload_to='profile-pics')

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.avatar.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.avatar.path)

recipe_platform_app/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from .constants import COUNTRIES_CHOICES
from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

    first_name = forms.CharField(max_length=100,
                                 required=True,
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name',
                                                               'class': 'form-control',
                                                               }))
    last_name = forms.CharField(max_length=100,
                                required=True,
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name',
                                                              'class': 'form-control',
                                                              }))
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Username',
                                                             'class': 'form-control',
                                                             }))
    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Email',
                                                           'class': 'form-control',
                                                           }))
    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password',
                                                                  'class': 'form-control',
                                                                  'data-toggle': 'password',
                                                                  'id': 'password',
                                                                  }))


class UpdateUserForm(ModelForm):
    username = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ["username", "email"]


class UpdateProfileForm(forms.ModelForm):
    first_name = forms.CharField(max_length=40, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    website_url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 2}))
    facebook_url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 2}))
    twitter_url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 2}))
    instagram_url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 2}))
    pinterest_url = forms.URLField(required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'rows': 2}))

    country_of_origin = forms.RadioSelect(choices=COUNTRIES_CHOICES)
    biography = forms.CharField(max_length=1000, widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 5}))
    avatar = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))

    class Meta:
        model = Profile
        fields = ["first_name", "last_name", "website_url", "facebook_url", "twitter_url", "instagram_url",
                  "pinterest_url", "country_of_origin", "biography", "avatar"]

recipe_platform_app/user/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.contrib.messages.views import SuccessMessageMixin
from .forms import SignUpForm, UpdateProfileForm, UpdateUserForm


class LoginUser(LoginView):
    template_name = "user_login.html"


class ChangePassword(SuccessMessageMixin,PasswordChangeView):
    template_name = "password_change.html"
    success_message = "Your password is changed successfully"
    success_url = reverse_lazy("home_page")


class RegisterUser(View):
    template_name = "user_registration.html"
    form_class = SignUpForm
    initial = {'key': 'value'}

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get("username")
            messages.success(request, f'Account created for {username}')

            return redirect(to='/')

        return render(request, self.template_name, {'form': form})


@login_required
def profile(request):
    if request.method == "POST":
        user_form = UpdateUserForm(request.POST, instance=request.user)
        profile_form = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() or profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile is updated")
            return redirect(to="user:user_profile")
    else:
        user_form = UpdateUserForm(instance=request.user)
        profile_form = UpdateProfileForm(instance=request.user.profile)

    return render(request, "user_profile.html", {"user_form": user_form, "profile_form": profile_form})

recipe_platform_app/user/templates/password_change.html
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}
{% load static %}



<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}{% endblock title %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/change_password.css' %}" />


  </head>
  <body>

<div class="flex-wrapper">
    <header>
        <!-- navbar -->
        <nav class = "main-nav">
          <ul>
                <li class="logo">
                  <div class = "navigation-top">
                    <a href = "{% url 'recipe:home_page' %}" class = "navigationbar-brand">
                      YUM<span>OO!</span>
                    </a>
                    <button type = "button" class = "navigationbar-toggler">
                      <i class = "fas fa-bars"></i>
                    </button>
                  </div>
                </li>
                <li>
                   <ul class="menu-items">
                      <li >
                        <a href = "{% url 'recipe:home_page' %}" class = "navigation-link">home</a>
                      </li>
                      <li >
                        <a href = "{% url 'recipe:about' %}" class = "navigation-link">about</a>
                      </li>
                      <li >
                        <a href = "{% url 'recipe:recipe_list' %}" class = "navigation-link">Recipes list</a>
                      </li>
                      <li >
                        <a href = "{% url 'recipe:category_list' %}" class = "navigation-link">Categories</a>
                      </li>
                      <li >
                        <a href = "{% url 'recipe:create_recipe' %}" class = "navigation-link">Upload Video</a>
                      </li>
                      <li >
                        <a href = "{% url 'store:store_page' %}" class = "navigation-link">Shop</a>
                      </li>

                      <li>
                            <div class="dropdown">
                              {% if user.is_authenticated %}

                                   <button class="dropbtn" type="button" aria-haspopup="true" aria-expanded="false">
                                                             <i class="fa fa-user" aria-hidden="true"></i>

                                   {% if user.first_name %}  Hello, {{ user.first_name }}!
                                    {% else %}Hello, {{ user.username }}!{% endif %}
                                    </button>
                                  <div class="dropdown-content">
                                          <a  href="{% url 'user:user_profile' %}">Profile</a>
                                          <a  href="{% url 'user:password_change' %}">Change password</a>
                                          <a  href="{% url 'user:logout' %}">Logout</a>
                                  </div>
                              {% else %}
                                        <button class="dropbtn" type="button" aria-haspopup="true" aria-expanded="false">
                                         Sign in
                                        </button>
                                      <div class="dropdown-content">
                                             <a  href="{% url 'user:login' %}">Login</a>
                                             <a  href="{% url 'user:register' %}">Register</a>
                                      </div>
                              {% endif %}
                            </div>
                      </li>
                   </ul>
            </li>

          </ul>

        </nav>
        <!-- end of navbar -->
    </header>


        <div class="content-section">
            <form method="post">
                {% csrf_token %}
                 <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Change Password</legend>
                    {{ form|crispy }}
                     </fieldset>
                <div class="form-group">
                        <input type="submit" value="Confirm" class="confirm-btn btn btn-light">
                </div>
            </form>
        </div>



     <footer class="footer-section">
         <hr class="border border-white">

            <div class="group-1">
                <div class="box">
                    <figure class="footer-logo" >
                  <div class = "navigation-top">
                    <a href = "{% url 'recipe:home_page' %}" class = "navigationbar-brand">
                      YUM<span>OO!</span>
                    </a>
                    <button type = "button" class = "navigationbar-toggler">
                      <i class = "fas fa-bars"></i>
                    </button>
                  </div>
                </li>
                    </figure>
                </div>
                <div class="box">
                    <h2>Contact info</h2>
                    <p>example@example.com</p>
                    <h2>Telephone number: </h2>
                    <p>00345817262</p>

                </div>
                <div class="box">
                    <h2>Social Media</h2>
                    <div class="red-social">
                        <a href="www.facebook.com" ><i class="fa fa-facebook"></i></a>
                        <a href="www.instagram.com" class="fa fa-instagram"></a>
                        <a href="www.twitter.com" class="fa fa-twitter"></a>
                        <a href="www.youtube.com" class="fa fa-youtube"></a>
                    </div>
                </div>
            </div>
            <div class="group-2">
                <small>&copy; 2022 <b>YUMOO!</b> - Copy Rights.</small>
            </div>
     </footer>
</div>
</body>
</div>

</html>

recipe_platform_app/user/templates/user_login.html
{% extends 'recipes/navbar_footer.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static '/css/login.css' %}" />

  <body>

  <div class="message">

      {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
    {% if next %}
        {% if user.is_authenticated %}
            <p>Your account doesn't have access to this page. To proceed,
                please log in with an account that has access.</p>
        {% else %}
            <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

  </div>

    <div class="center">
      <h1>Login</h1>
      <form method="post" action="{% url 'user:login' %}">
                  {% csrf_token %}

        <div class="txt_field">

            {{ form.username }}
          <label>Username</label>
        </div>
        <div class="txt_field">

            {{ form.password }}
          <label>Password</label>
        </div>
        <div class="pass">Forgot Password?</div>
        <input type="submit" value="Login">
        <div class="signup_link">
          Not a member? <a href="{% url 'user:register' %}">Signup</a>
        </div>
      </form>
    </div>

  </body>


{# <a href="{% url 'social:begin' 'github' %}" class="btn btn-link btn-lg active btn-block">Sign in with GitHub</a>#}

{% endblock %}

recipe_platform_app/user/templates/user_profile.html
{% extends "recipes/navbar_footer.html" %}
{% load static %}

{% block title %}<title> Profile YUMOO!</title>{% endblock title %}


{% block content %}
    <link rel="stylesheet" href="{% static '/css/profile.css' %}" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

{#    new html#}
<body>
  <div class="wrapper">

    <div class="card">
      <div class="img">
        <img src="{{ user.profile.avatar.url }}" alt="Image" width="100%">
      </div>

      <div class="cnt">
        <div class="name">{{ user.profile.first_name }} {{ user.profile.last_name }}</div>
        <div class="txt">{{ user.profile.biography}}
      </div>
        <i class="fas fa-thumbtack"></i>
        <strong>{{ user.profile.country_of_origin}}</strong>

        <div class="card-inf">
          <div class="item">
            <div class="title">3.2M</div>
            <div class="txt">Folowers</div>
          </div>

          <div class="item">
            <div class="title">56</div>
            <div class="txt">Folowing</div>
          </div>

          <div class="item">
            <div class="title">1.2K</div>
            <div class="txt">Articles</div>
          </div>

          <div class="item">
            <div class="title">1.1K</div>
            <div class="txt">Works</div>
          </div>
        </div>

        <div class="card-social">
          <a href="{{ user.profile.facebook_url }}" class="facebook">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="{{ user.profile.twitter_url }}" class="twitter">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="{{ user.profile.instagram_url }}" class="instagram">
            <i class="fab fa-instagram"></i>
          </a>
            <a href="{{ user.profile.website_url }}" class="youtube">
            <i class="fab fa-youtube"></i>
          </a>

        </div>

        <div class="card-button">
          <button class="btn-blue">Message</button>
          <button class="btn-orange">Follow</button>
        </div>

      </div>
    </div>

  </div>
</body>

{#  new html end   #}


{#    <div class="row my-3 p-3">#}
{#        <img class="rounded-circle account-img" src="{{ user.profile.avatar.url }} " style="cursor: pointer; width: 100px"/>#}
{#    </div>#}
{#    {% if user_form.errors %}#}
{#        <div class="alert alert-danger alert-dismissible" role="alert">#}
{#            <div id="form_errors">#}
{#                {% for key, value in user_form.errors.items %}#}
{#                    <strong>{{ value }}</strong>#}
{#                {% endfor %}#}
{#            </div>#}
{#            <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                <span aria-hidden="true">&times;</span>#}
{#            </button>#}
{#        </div>#}
{#    {% endif %}#}
{#    <div class="form-content">#}
{#        <form method="post" enctype="multipart/form-data">#}
{#            {% csrf_token %}#}
{#            <div class="form-row">#}
{#                <div class="col-md-5">#}
{#                    <div class="form-group">#}
{#                        <label class="small mb-1">Username:</label>#}
{#                        {{ user_form.username }}#}
{#                        <label class="small mb-1">Email:</label>#}
{#                        {{ user_form.email }}#}
{#                    </div>#}
{#                    <div class="form-group">#}
{#                        <a href="{% url 'user:password_change' %}">Change Password</a>#}
{#                        <hr>#}
{#                        <label class="small mb-1">First Name:</label>#}
{#                        {{ profile_form.first_name }}#}
{#                        <label class="small mb-1">Last Name:</label>#}
{#                        {{ profile_form.last_name }}#}
{#                        <label class="small mb-1">Website:</label>#}
{#                        {{ profile_form.website_url }}#}
{#                        <label class="small mb-1">Facebook Page:</label>#}
{#                        {{ profile_form.facebook_url }}#}
{#                        <label class="small mb-1">Twitter:</label>#}
{#                        {{ profile_form.twitter_url }}#}
{#                        <label class="small mb-1">Instagram:</label>#}
{#                        {{ profile_form.instagram_url }}#}
{#                        <label class="small mb-1">Pinterest:</label>#}
{#                        {{ profile_form.pinterest_url }}#}
{#                        <label class="small mb-1">Country:</label>#}
{#                        {{ profile_form.country_of_origin }}#}
{#                        <hr>#}
{#                        <label class="small mb-1">Change Avatar:</label>#}
{#                        {{ profile_form.avatar }}#}
{#                        <hr>#}
{##}
{#                    </div>#}
{#                    <label class="small mb-1">Bio:</label> {{ profile_form.biography }}#}
{#                </div>#}
{#            </div>#}
{#            <br><br>#}
{#            <button type="submit" class="btn btn-dark btn-lg">Save Changes</button>#}
{#            <button type="reset" class="btn btn-dark btn-lg">Reset</button>#}
{#        </form>#}
{#    </div>#}

{% endblock content %}

recipe_platform_app/user/templates/user_registration.html
{% extends "recipes/navbar_footer.html" %}
{% load static %}
{% block title %} Register Page {% endblock title%}
{% block content %}
    <link rel="stylesheet" href="{% static '/css/register.css' %}" />
<body>
    <div class="center">
      <h1>Creat a New Account</h1>
      <form method="post" action="{% url 'user:register' %}">
                  {% csrf_token %}
                    {% if form.errors %}
                        <div class="message">
                            <div>
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                            </div>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true"></span>
                            </button>
                        </div>
                    {% endif %}

        <div class="txt_field">
            {{ form.first_name }}
            <label>First Name</label>
        </div>

        <div class="txt_field">
            {{ form.last_name }}
            <label>First Name</label>
        </div>

        <div class="txt_field">
            {{ form.username }}
            <label>Username</label>
        </div>

        <div class="txt_field">
            {{ form.email }}
            <label>Email</label>
        </div>

        <div class="txt_field">

            {{ form.password1 }}
          <label>Password</label>
        </div>

      <div class="txt_field">
            {{ form.password2 }}
          <label>Confirm Password</label>
      </div>


        <input type="submit" value="Sign Up">
        <div class="login_link">
          Have an account? <a href="{% url 'user:login' %}">Log in here</a>
        </div>
      </form>
    </div>


</body>

{% endblock content %}