recipe_platform_app/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

recipe_platform_app/recipe_platform_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path('oauth/', include('social_django.urls', namespace='social')),
               path('admin/', admin.site.urls),
               path('', include('recipe.urls')),
               path('cart/', include('cart.urls', namespace='cart')),
               path('store/', include('store.urls', namespace='store')),

               path('accounts/', include('user.urls')),

               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from store.views import *

app_name = 'store'

urlpatterns = [
                  path('', store_page, name='store_page'),
                  path('<slug:category_slug>', store_page, name='product_list_by_category'),
                  path('<int:id>/<slug:slug>', product_detail, name='product_detail'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/store/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from PIL import Image
from .constants import PRODUCTS_CATEGORIES_CHOICES


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)

    class Meta:
        ordering = ("name",)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product_list_by_category', args=[self.slug])


class Products(models.Model):
    # category = models.CharField(max_length=30, null=True, blank=True, default="Other",
    #                             choices=PRODUCTS_CATEGORIES_CHOICES)
    category = models.ForeignKey(Category, related_name="products", on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, null=True)
    description = models.TextField(max_length=500)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    image = models.ImageField(default="mountain.jpg", upload_to='products-pics', null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)
        index_together = ('id', 'slug')

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.id, self.slug])

    # # in case we don't have an image for one product we will not get an error.
    # # if there is no image uploaded we will get an empty string url.
    # # @property decorator which let us access this as an attribute not as a method
    @property
    def imageURL(self):

        try:
            url = self.image.url
        except:
            url = ''
        return url

recipe_platform_app/store/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from cart.forms import CartAddProductForm


def store_page(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Products.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {'products': products, 'category': category, 'categories': categories}
    return render(request, 'store/product/store.html', context)


def product_detail(request, id, slug):
    product = get_object_or_404(Products, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'store/product/product_detail.html',
                  {'product': product, 'cart_product_form': cart_product_form}
                  )

recipe_platform_app/store/templates/store/product/product_detail.html
{% extends "recipes/navbar_footer.html" %}
{% load static %}

<!-- -->
{% block navbar_content %}

{#           <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />#}
{#<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">#}
	<link  rel="stylesheet" href="{% static '/css/product_detail.css/' %}">


    <!-- CSS only -->

           <div class="form-inline my-2 my-lg-0">

        <div class="cart_container">
            {% with total_items=cart|length %}
              {% if total_items  %}
                  <a href="{% url 'cart:cart_detail' %}">
                        <img  class="cart_icon" src="{% static 'images/cart.png' %}">
                  </a>

                  <p class="cart-total">{{ total_items }}</p>

                  {% else %}

                  <a href="#">
                        <img  class="cart_icon" src="{% static 'images/cart.png' %}">
                  </a>

                  <p class="cart_total" >0</p>

              {% endif %}
            {% endwith %}


      </div>



      </div>

{% endblock navbar_content %}



{% block content %}
{#	<link  rel="stylesheet" href="{% static '/css/product_detail.css/' %}">#}

    <h1 class="page_title">Product Detail Page</h1>

<div class="card my-4 border border-dark">
  <div class="card-body">

            <img class=" border-dark" src="{% if product.image %} {{product.image.url}}
                                          {% else %} {% static 'images/placeholder.png' %} {% endif %}"   >

            <h2 class="card-title">{{ product.name }}</h2>
            <p class="card-text"><b>Price:</b> ${{ product.price }}</p>
            <h6 class="category">Category: <a href="{{ product.category.get_absolute_url }}">
              {{ product.category }}
            </a></h6>

            <form  class="form" action="{% url 'cart:cart_add' product.id%}" method="post">
                {{ cart_product_form }}
                {% csrf_token %}
                <input type="submit" value="Add to Cart">

            </form>
            <p class="card-text"><b>Description:</b> {{ product.description }}</p>



  </div>

</div>

<!-- -->
{% endblock content %}

recipe_platform_app/store/templates/store/product/store.html
{% extends 'recipes/navbar_footer.html' %}
{% load static %}

{% block navbar_content %}
 <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
	<link  rel="stylesheet" href="{% static '/css/store.css' %}">


    <!-- CSS only -->
        <div class="cart_container">
            {% with total_items=cart|length %}
              {% if total_items  %}
                  <a href="{% url 'cart:cart_detail' %}">
                        <img  class="cart_icon" src="{% static 'images/cart.png' %}">
                  </a>

                  <p class="cart-total">{{ total_items }}</p>

                  {% else %}

                  <a href="#">
                        <img  class="cart_icon" src="{% static 'images/cart.png' %}">
                  </a>

                  <p class="cart_total" >0</p>

              {% endif %}
            {% endwith %}


      </div>

{% endblock navbar_content %}

{% block content %}
	<link  rel="stylesheet" href="{% static '/css/store.css' %}">


{# new html#}

    <div class="section-body">

        {% if category %} {{ category.name }}
        {% else %}
        {% endif %}
            <div class="vertical-nav" >
                <ul style="background: linear-gradient(to right , black,#3d3d3d, #2a2929, #3d3d3d );;
                font-size: 20px; width: 250px; border:#E34513FF solid 1px;
                 border-radius: 9px;
                 box-shadow: 0 5px 5px rgb(227,69,19); font-weight: bold;
                    ">
                    <h4 style="font-weight: bold; font-size: 30px; color: #E34513FF"><left>Category</left></h4>
                    <li  {% if not category %} {% endif %}>
                            <a style="color: white" href="{% url 'store:store_page' %}">All</a>
                    </li>
                {% for c in categories %}
                    <li {%  if category.slug == c.slug %}{% endif %}>
                        <a style="color: white" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                {% endfor %}
                </ul>
            </div>

            <div class="gallery-main" style="margin-left:25%;padding:1px 16px;height:1000px;">
                <div class="Adventure" id="Adventure">
                    <h2 style="color: #E34513FF; font-weight: bold">{% if category %} {{ category.name }}{% else %}Products{% endif %}</h2>

                    <div class="gallery">
                        {% for product in products %}
                        <div class="image-holder">
                            <a href="{{product.get_absolute_url}}">
                       <img src="{% if product.image %} {{product.image.url}}
                                 {% else %} {% static 'images/placeholder.png' %} {% endif %}"
                            >
                            <div class="desc">
                                <h6 style="margin-top: 20px;"><strong>{{ product.name }}</strong></h6>
                                Price : ${{product.price}}
                                <br>

                                <button>
                                    <a  href="{{product.get_absolute_url}}">
                                        View
                                    </a>
                                </button>
                            </div>
                        </div>
                    {% endfor %}
                    </div>

                </div>
            </div>

            <br>

        </div>


    </body>







{# end of ew html   #}
{#    {% if category %} {{ category.name }}#}
{#    {% else %}#}
{#    {% endif %}#}
{##}
{##}
{##}
{#    <ul class="store_container">#}
{##}
{#    <li class=row_li">#}
{#        <div id="sidebar">#}
{##}
{#                 <h3>Categories</h3>#}
{#                    <ul>#}
{#                        <li {% if not category %} class="selected" {% endif %}>#}
{#                            <a href="{% url 'store:store_page' %}">All</a>#}
{#                        </li>#}
{#                        {% for c in categories %}#}
{#                            <li {%  if category.slug == c.slug %} class="selected"{% endif %}>#}
{#                            <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>#}
{#                            </li>#}
{#                        {% endfor %}#}
{#                    </ul>#}
{#        </div>#}
{##}
{#    </li>#}
{#<li class="row_li">#}
{#       <h1> {% if category %} {{ category.name }}{% else %}Products{% endif %}</h1>#}
{#</li>#}
{#        {% for product in products %}#}
{##}
{#            <li class=" product_cards">#}
{#            <ul>#}
{#            <li>#}
{#            <div class="card" style="width: 18rem;">#}
{#                <a href="{{product.get_absolute_url}}">#}
{#                        <img class="thumbnail"#}
{#                             src="{% if product.image %} {{product.image.url}}#}
{#                                  {% else %} {% static 'images/placeholder.png' %} {% endif %}">#}
{#                </a>#}
{#                <div class = "box-element product">#}
{#                    <h6><strong>{{ product.name }}</strong></h6>#}
{#                    <hr>#}
{#                    <a class="btn btn-outline-success" href="{{product.get_absolute_url}}">View</a>#}
{#                    <h4 style="display: inline-block; float: right">${{product.price}}</h4>#}
{##}
{##}
{#                </div>#}
{#            </div>#}
{#            </li>#}
{#            </ul>#}
{#            </li>#}
{#        {% endfor %}#}
{#    </ul>#}

{% endblock content %}