recipe_platform_app/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

recipe_platform_app/recipe/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from recipe.views import *
from user.views import LoginUser
from user.views import profile

app_name = 'recipe'

urlpatterns = [
                  path('play-video/', play_video, name="play-video"),
                  path('', home, name='home_page'),
                  path("profile/", profile, name='user_profile'),
                  path("login/", LoginUser.as_view(), name='login'),
                  path('recipes-list', RecipeListView.as_view(), name='recipe_list'),
                  path('recipe/<int:pk>', RecipeDetailView.as_view(), name='recipe_detail'),
                  path('recipe/create/', RecipeCreateView.as_view(), name='create_recipe'),
                  path('recipe/<int:pk>/update/', RecipeUpdateView.as_view(), name='update_recipe'),
                  path('recipe/<int:pk>/delete', RecipeDeleteView.as_view(), name='delete_recipe'),
                  path('about/', about, name='about'),
                  path('recipe/<int:pk>/add-comment', add_comment, name='add-comment'),
                  path('recipe/<int:pk>/delete-comment', comment_delete, name='delete-comment'),
                  path('like/<int:pk>', LikeView, name='like_recipe'),
                  path('add_category/', AddCategoryView.as_view(), name='add-category'),
                  path('category/<str:cats>/', CategoryView, name='category'),
                  path('category_list/', CategoryListView, name='category_list'),
                  path('search/', search, name='search_page'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/recipe_platform_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path('oauth/', include('social_django.urls', namespace='social')),
               path('admin/', admin.site.urls),
               path('', include('recipe.urls')),
               path('cart/', include('cart.urls', namespace='cart')),
               path('store/', include('store.urls', namespace='store')),

               path('accounts/', include('user.urls')),

               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from store.views import *

app_name = 'store'

urlpatterns = [
                  path('', store_page, name='store_page'),
                  path('<slug:category_slug>', store_page, name='product_list_by_category'),
                  path('<int:id>/<slug:slug>', product_detail, name='product_detail'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/user/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from user.views import LoginUser, ChangePassword, RegisterUser, profile

app_name = "user"
urlpatterns = [
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("changepassword/", ChangePassword.as_view(), name="password_change"),
    path("register/", RegisterUser.as_view(), name="register"),
    path("profile/", profile, name="user_profile")
]

recipe_platform_app/recipe/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from embed_video.fields import EmbedVideoField


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(
        default='mountain.jpg',
        upload_to='category_images',
        null=True,
        blank=True
    )

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse('recipe_list')

    @property
    # in case we don't have an image for one product we will not get an error.
    # if there is no image uploaded we will get an empty string url.
    # @property decorator which let us access this as an attribute not as a method
    def imageURL(self):
        try:
            url = self.image.url
        except ValueError:
            url = ''
        return url


choices = Category.objects.all().values_list('name', 'name')

recipe_category_choices = []

for item in choices:
    recipe_category_choices.append(item)


class Recipe(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=500)
    ingredients = models.TextField(max_length=500)
    number_of_portions = models.CharField(max_length=100)
    preparation_time = models.CharField(max_length=30)
    total_time = models.CharField(max_length=30)
    upload_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    video = models.FileField(upload_to='videos/', blank=True)
    likes = models.ManyToManyField(User, related_name='recipe_page', blank=True)
    category = models.CharField(max_length=30, null=True, blank=True, default="Other",
                                choices=recipe_category_choices
                                )
    external_video = EmbedVideoField(verbose_name="My online video",
                                     help_text="Your recipe video", blank=True
                                     )

    def get_absolute_url(self):
        return reverse("recipe_detail", kwargs={"pk": self.pk})

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["pk"]


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, related_name="comments",
                               on_delete=models.CASCADE)
    commenter_name = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.recipe.title}, {self.commenter_name}'

recipe_platform_app/recipe/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_body',)
        widgets = {
            'comment_body': forms.Textarea(attrs={'class': 'form-control'})
        }

recipe_platform_app/recipe/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import View,ListView, UpdateView, DeleteView, CreateView
from store.models import Products
from .forms import CommentForm
from .mixins import YouTube
from .models import *
from hitcount.views import HitCountDetailView




def home(request):
    return render(request, 'recipes/index.html', {})


def about(request):
    return render(request, 'recipes/about.html', {'title': 'about page'})


def play_video(request):
    vid_id = request.GET.get("vid_id")

    vid_data = YouTube(vid_id=vid_id).get_video()

    context = {
        "vid_data": vid_data,
    }
    return render(request, 'recipes/play_video.html', context)


class RecipeListView(ListView):
    template_name = 'recipes/recipes_list.html'
    model = Recipe
    context_object_name = 'recipes'


class RecipeDetailView(HitCountDetailView):
    template_name = 'recipes/recipe_detail.html'
    model = Recipe
    count_hit = True

    def get_context_data(self, **kwargs):
        recipe = Recipe.objects.get(pk=self.object.pk)

        context = super().get_context_data(**kwargs)
        context['recipes'] = Recipe.objects.all()
        context['num_comments'] = Comment.objects.filter(recipe=recipe).count()
        context['total_likes'] = recipe.total_likes()
        return context


class RecipeUpdateView(PermissionRequiredMixin, UpdateView):
    template_name = 'recipes/update_recipe.html'
    model = Recipe
    success_url = reverse_lazy('recipe:recipe_list')
    fields = ['title', 'category', 'description', 'ingredients',
              'number_of_portions', 'preparation_time', 'total_time',
              'video', 'external_video']
    permission_required = "recipe.change_recipe"

    # only the author of the recipe is allowed to update it
    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.author

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeCreateView(LoginRequiredMixin, CreateView):
    template_name = 'recipes/create_recipe.html'
    model = Recipe
    success_url = reverse_lazy('recipe_list')
    fields = ['title', 'description', 'ingredients', 'number_of_portions',
              'preparation_time', 'total_time', 'video',
              'external_video']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class RecipeDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'recipes/delete_recipe.html'
    model = Recipe
    success_url = reverse_lazy('home_page')
    permission_required = "recipe.delete_recipe"

    def test_func(self):
        recipe = self.get_object()
        return self.request.user == recipe.author


class AddCategoryView(PermissionRequiredMixin, CreateView):
    model = Category
    template_name = 'recipes/add_category.html'
    fields = '__all__'
    permission_required = 'add_category'


def CategoryView(request, cats):
    category_recipes = Recipe.objects.filter(category=cats.title())

    return render(request, 'recipes/categories.html',
                  {'cats': cats, 'category_recipes': category_recipes})


def CategoryListView(request):
    cat_menu_list = Category.objects.all()
    return render(request, 'recipes/category_list.html',
                  {'cat_menu_list': cat_menu_list})


def add_comment(request, pk):
    # on click at add comment, will take the formation from db for the particular recipe

    recipe = Recipe.objects.get(id=pk)

    if request.method == 'POST':
        # if the request is POST will take all the info related to that recipe form

        form = CommentForm(request.POST, instance=recipe)
        if form.is_valid():
            name = request.user
            body = form.cleaned_data['comment_body']
            # and we save the comment info

            c = Comment(recipe=recipe, commenter_name=name,
                        comment_body=body, date_added=datetime.now())
            c.save()
            return redirect(reverse('recipe:recipe_detail', args=[recipe.pk]))

    else:
        form = CommentForm()

    context = {
        'form': form,
    }

    return render(request, 'recipes/add_comment.html', context)


@login_required
def comment_delete(request, pk):
    Comment.objects.get(pk=pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def LikeView(request, pk):
    recipe = get_object_or_404(Recipe, id=request.POST.get('recipe_id'))
    recipe.likes.add(request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def search(request):
    if request.method == 'POST':
        searched = request.POST.get('searched')
        recipes = Recipe.objects.filter(title__icontains=searched)
        categories = Category.objects.filter(name__icontains=searched)
        products = Products.objects.filter(name__icontains=searched)
        context = {
            'searched': searched,
            'recipes': recipes,
            'categories': categories,
            'products': products,
        }
        return render(request, 'recipes/search.html', context
                      )
    else:
        return render(request, 'recipes/search.html', {})

recipe_platform_app/recipe/templates/recipes/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    {% block title %}{% endblock title %}

    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
            crossorigin="anonymous"
    />
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static '/css/main.css/' %}">


</head>
<body >
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand logo" href="{% url 'recipe:home_page' %}">YUMOO!</a>
            <button class="navbar-toggler"
                    type="button"
                    data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'recipe:about' %}">About</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'recipe:recipe_list' %}"> Recipes List<span class="sr-only">(Current)</span></a>
                    </li>


                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'recipe:create_recipe' %}">Add Recipe</a>
                    </li>

                    <li class="nav-item active">
                                <a class="nav-link" href="{% url 'recipe:category_list' %}">Recipes Categories</a>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'store:store_page' %}">Shop</a>
                    </li>
                </ul>
            </div>
        <form class="d-flex" style="padding-right: 50px" method="POST" action="{% url 'recipe:search_page' %}">
            {% csrf_token %}
            <input class="form-control me-2"
            type="search" placeholder="Search" aria-label="Search" name="searched">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </form>

        {% block navbar_content %} {% endblock navbar_content %}



            <div style="padding-left: 20px" class="navbar-nav ml-auto">
                <div class="nav-item btn-group dropleft">
                    {% if user.is_authenticated %}
                        <button type="button" class="btn btn-success dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                            {% if user.first_name %}Hello, {{ user.first_name }}!
                            {% else %}Hello, {{ user.username }}!{% endif %}
                        </button>
                    <div class="dropdown-menu">
                        <a class="dropdown-item " href="{% url 'user:user_profile' %}">Profile</a>
                        <a class="dropdown-item " href="{% url 'user:password_change' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item " href="{% url 'user:logout' %}">Logout</a>
                    </div>

                    {% else %}
                        <button type="button" class="btn btn-danger dropdown-toggle"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Sign In
                        </button>
                        <div class="dropdown-menu">

                            <a class="dropdown-item " href="{% url 'user:login' %}">Login</a>
                            <a class="dropdown-item " href="{% url 'user:register' %}">Register</a>
                        </div>
                    {% endif %}
                </div>

            </div>
        </nav>

        <div class="recipe_container">
              {% if messages %} {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">{{ message }}</div>
              {% endfor %} {% endif %} {% block content %} {% endblock %}
        </div>




    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
            crossorigin="anonymous"></script>
    <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
            integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
            crossorigin="anonymous"></script>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
            integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
            crossorigin="anonymous"></script>

    <script crossorigin="anonymous"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script crossorigin="anonymous"
            integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>


</body>
</html>

recipe_platform_app/recipe/templates/recipes/index.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}<title>YUMOO!</title>{% endblock title %}
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="static/css/home_page.css" />
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800;900&display=swap" rel="stylesheet">
  </head>
  <body>

    <!-- navbar -->
    <nav class = "navigationbar">
      <div class = "navigation-top">
        <a href = "{% url 'recipe:home_page' %}" class = "navigationbar-brand">
          YUM<span>OO!</span>
        </a>
        <button type = "button" class = "navigationbar-toggler">
          <i class = "fas fa-bars"></i>
        </button>
      </div>

      <div class = "navigationbar-collapse">
        <ul class = "navigationbar-nav">
          <li class = "navigation-item">
            <a href = "{% url 'recipe:home_page' %}" class = "navigation-link">home</a>
          </li>
          <li class = "navigation-item">
            <a href = "{% url 'recipe:about' %}" class = "navigation-link">about</a>
          </li>
          <li class = "navigation-item">
            <a href = "{% url 'recipe:recipe_list' %}" class = "navigation-link">Recipes list</a>
          </li>
          <li class = "navigation-item">
            <a href = "{% url 'recipe:category_list' %}" class = "navigation-link">Categories</a>
          </li>
          <li class = "navigation-item">
            <a href = "{% url 'recipe:create_recipe' %}" class = "navigation-link">Upload Video</a>
          </li>
          <li class = "navigation-item">
            <a href = "{% url 'store:store_page' %}" class = "navigation-link">Shop</a>
          </li>

          <li  class = "navigation-item" >
                  {% if user.is_authenticated %}

                       <button class="login-home-page-btn" type="button" aria-haspopup="true" aria-expanded="false">
                          <a  href="{% url 'user:user_profile' %}" class = "navigation-link">
                          <i class="fa fa-user" aria-hidden="true"></i>
                              {% if user.first_name %}  Hello, {{ user.first_name }}!
                        {% else %}Hello, {{ user.username }}!{% endif %}

                        </a>
                        </button>

                  {% else %}
                            <button class="login-home-page-btn" type="button" aria-haspopup="true" aria-expanded="false">
                                <a  href="{% url 'user:login' %}" class = "navigation-link">Sign in </a>
                            </button>
                  {% endif %}
          </li>

        </ul>
      </div>


    </nav>
    <!-- end of navbar -->

<body>
    <!-- header -->
    <div class = "header">
      <!-- bg video -->

        <video autoplay muted loop id = "bg-video">
          <source src="media/videos/home_page_video.mp4" type="video/mp4" />
        </video>

      <!-- end of bg video -->

      <div class = "recipe_container">
        <!-- hero section -->
        <div class = "hero-content">
          <div class = "hero-content-change">
            <div>
              <span>
                <i class = "fas fa-apple-alt"></i>
              </span>
              <h3>
                <div class = "line"></div>
                <span>It is all about food</span>
                <div class = "line"> </div>
              </h3>
              <h1 class = "hero-lg-text">
                  create, share, follow, learn
              </h1>
            </div>
          </div>

          <blockquote class = "hero-quote">
            <span>
              <i class = "fas fa-quote-left"></i>
            </span>
            A Recipe has no soul. You as the cook must bring soul to the recipe. Join YUMOO! NOW!
            <span>
              <i class = "fas fa-quote-right"></i>
            </span>
          </blockquote>

          <button type = "button" class = "hero-btn">
            <a href="{% url 'recipe:recipe_list' %}">Start Now</a>
          </button>

        </div>
        <!-- end of hero section -->
      </div>
    </div>
    <!-- end of header -->
</header>

    <script src = "{% static '/js/home_page.js/' %}"></script>
  </body>

recipe_platform_app/recipe/templates/recipes/navbar_footer.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% block title %}{% endblock title %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800;900&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
          integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
          crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static '/css/navbar_footer.css' %}" />

  </head>
<div class="nf_flex-wrapper">
<header>
    <!-- navbar -->
    <nav class = "nf_main-nav">
      <ul>
            <li class="nf_logo">
                <div class = "nf_navigation-top">
                <a href = "{% url 'recipe:home_page' %}" class = "navigationbar-brand">
                  YUM<span>OO!</span>
                </a>
                <button type = "button" class = "navigationbar-toggler">
                  <i class = "fas fa-bars"></i>
                </button>
              </div>
            </li>
          <li class="nf_search_bar_box">
              <form class="nf_d-flex"  method="POST" action="{% url 'recipe:search_page' %}">
                {% csrf_token %}
                <input class="nf_search_bar_input"
                type="search" placeholder="Search" aria-label="Search" name="searched">
                <button class="nf_search_bar_btn" type="submit"><i class="fa fa-search" aria-hidden="true"></i>
</button>
            </form>
          </li>
            <li>
               <ul class="nf_menu-items">
                  <li >
                    <a href = "{% url 'recipe:home_page' %}" class = "nf_navigation-link">home</a>
                  </li>
                  <li >
                    <a href = "{% url 'recipe:about' %}" class = "nf_navigation-link">about</a>
                  </li>
                  <li >
                    <a href = "{% url 'recipe:recipe_list' %}" class = "nf_navigation-link">Recipes list</a>
                  </li>
                  <li >
                    <a href = "{% url 'recipe:category_list' %}" class = "nf_navigation-link">Categories</a>
                  </li>
               {% if request.user.is_authenticated %}
                  <li >
                    <a href = "{% url 'recipe:create_recipe' %}" class = "nf_navigation-link">Upload Video</a>
                  </li>
               {% endif %}
                  <li >
                    <a href = "{% url 'store:store_page' %}" class = "nf_navigation-link">Shop</a>
                  </li>
                    <li>

                        {% block navbar_content %}
                        {% endblock navbar_content %}


                    </li>
                  <li>
                        <div class="nf_dropdown">
                          {% if user.is_authenticated %}

                               <button class="nf_dropbtn" type="button" aria-haspopup="true" aria-expanded="false">
                                                         <i class="fa fa-user" aria-hidden="true"></i>

                               {% if user.first_name %}  Hello, {{ user.first_name }}!
                                {% else %}Hello, {{ user.username }}!{% endif %}
                                </button>
                              <div class="nf_dropdown-content">
                                      <a  href="{% url 'user:user_profile' %}">Profile</a>
                                      <a  href="{% url 'user:password_change' %}">Change password</a>
                                      <a  href="{% url 'user:logout' %}">Logout</a>
                              </div>
                          {% else %}
                                    <button class="nf_dropbtn" type="button" aria-haspopup="true" aria-expanded="false">
                                     Sign in
                                    </button>
                                  <div class="nf_dropdown-content">
                                         <a  href="{% url 'user:login' %}">Login</a>
                                         <a  href="{% url 'user:register' %}">Register</a>
                                  </div>
                          {% endif %}
                        </div>
                  </li>
               </ul>
        </li>

      </ul>

    </nav>
    <!-- end of navbar -->
</header>

      {% block content %}{% endblock content %}

<!-- footer -->


 <footer class="nf_footer-section">
     <hr class="nf_border border-white">

        <div class="nf_group-1">
            <div class="nf_box">
                <figure class="nf_footer-logo" >
              <div class = "nf_navigation-top">
                <a href = "{% url 'recipe:home_page' %}" class = "navigationbar-brand">
                  YUM<span>OO!</span>
                </a>
                <button type = "button" class = "navigationbar-toggler">
                  <i class = "fas fa-bars"></i>
                </button>
              </div>
            </li>
                </figure>
            </div>
            <div class="nf_box">
                <h2>Contact info</h2>
                <p>example@example.com</p>
                <h2>Telephone number: </h2>
                <p>00345817262</p>

            </div>
            <div class="nf_box">
                <h2>Social Media</h2>
                <div class="nf_red-social">
                    <a href="#" ><i class="fa fa-facebook"></i></a>
                    <a href="#" class="fa fa-instagram"></a>
                    <a href="#" class="fa fa-twitter"></a>
                    <a href="#" class="fa fa-youtube"></a>
                </div>
            </div>
        </div>
        <div class="nf_group-2">
            <small>&copy; 2022 <b>YUMOO!</b> - Copy Rights.</small>
        </div>
 </footer>
</div>