recipe_platform_app/cart/urls.py
from django.urls import path

from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

recipe_platform_app/recipe_platform_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path('oauth/', include('social_django.urls', namespace='social')),
               path('admin/', admin.site.urls),
               path('', include('recipe.urls')),
               path('cart/', include('cart.urls', namespace='cart')),
               path('store/', include('store.urls', namespace='store')),

               path('accounts/', include('user.urls')),

               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/store/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from store.views import *

app_name = 'store'

urlpatterns = [
                  path('', store_page, name='store_page'),
                  path('<slug:category_slug>', store_page, name='product_list_by_category'),
                  path('<int:id>/<slug:slug>', product_detail, name='product_detail'),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform_app/cart/models.py
from django.db import models

# Create your models here.

recipe_platform_app/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )

recipe_platform_app/cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST, require_http_methods
from cart.cart import Cart
from store.models import Products
from .forms import CartAddProductForm


@require_POST
# @require_http_methods(["POST"])
# require http method, check it!
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial=
            {
                'quantity': item['quantity'],
                'override': True,
            }
        )
    return render(request, 'cart/detail.html', {'cart': cart})

recipe_platform_app/cart/templates/cart/detail.html
{% extends 'recipes/navbar_footer.html' %}
{% load static %}
{% block content %}
{% block navbar_content %}

    <link  rel="stylesheet" href="{% static '/css/cart_detail.css/' %}">


    <!-- CSS only -->

           <div class="form-inline my-2 my-lg-0">

        <div class="cart_container">
            {% with total_items=cart|length %}
              {% if total_items  %}
                  <a href="{% url 'cart:cart_detail' %}">
                        <img  class="cart_icon" src="{% static 'images/cart.png' %}">
                  </a>

                  <p class="cart-total">{{ total_items }}</p>

                  {% else %}

                  <a href="#">
                        <img  class="cart_icon" src="{% static 'images/cart.png' %}">
                  </a>

                  <p class="cart_total" >0</p>

              {% endif %}
            {% endwith %}


      </div>



      </div>

{% endblock navbar_content %}



    	<link  rel="stylesheet" href="{% static '/css/cart_detail.css' %}">



    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class=" continue_shopping btn btn-outline-dark" href="{% url 'store:store_page' %}">&#x2190; Continue Shopping</a>

                <br>
                <br>

                <table class="table">
                    <tr class="total">
                        <th><h5 class="total">Total: <strong>${{ cart.get_total_price }}</strong></h5></th>
                        <th>
                            <a style="float: right; margin: 5px"
                               class=" checkout btn btn-outline-success"
                               href="#">Checkout</a>
                        </th>

                    </tr>
                </table>
            </div>
            <br>
            <div class="box-element">
                <div class="cart-row">
                    <div style="flex:1"></div>
                    <div style="flex:2"></div>

                    <div style="flex:2"><strong>Item</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity</strong></div>
                    <div style="flex:1"><strong>Total</strong></div>
                </div>
                {% for item in cart %}
                        <div class="cart-row">

                         <div style="flex:1">
                                <form class="remove" action=" {% url 'cart:cart_remove' item.product.id %}" method="post">
                                    <input type="submit" value="Remove">
                                    {% csrf_token %}
                                </form>
                        </div>
                            <div style="flex:2">
                                <a href="{{ item.product.get_absolute_url }}">
                                    <img class="row-image"
                                         src="{% if item.product.image %}{{ item.product.image.url }}
                                        {% else %} {% static 'images/placeholder.png' %}{% endif %}">
                                </a>
                            </div>



                            <div style="flex:2">{{ item.product.name}}</div>
                            <div style="flex:1">{{ item.price}}</div>
                            <div style="flex:1">
                                <form class="update" action="{% url 'cart:cart_add' item.product.id %}" method="post">

                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    {% csrf_token %}
                                     <input type="submit" value="Update">

                                </form>
                            </div>
                            <div style="flex:1">${{ item.total_price}}</div>

                        </div>

                    <hr>
                {% endfor %}

            </div>

        </div>
    </div>

{% endblock content %}